[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
]
# STM32F405RGT6 (Cortex-M4)
runner = """qemu-system-arm \
    -machine netduinoplus2 \
    -nographic \
    -semihosting-config enable=on,target=native \
    -kernel \
    """