[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]
runner = "probe-rs run --chip RP2040"

[target.'thumbv8m.main-none-eabihf']
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]
runner = "probe-rs run --chip RP235x"

[env]
DEFMT_LOG = "info"