[package]
name = "taskette"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
heapless = "0.9.1"
log = "0.4.28"

[dev-dependencies]
cortex-m-semihosting = "0.5.0"
goolog = "0.11.0"
panic-semihosting = "0.6.0"
static_cell = "2.1.1"
