[package]
name = "taskette-cortex-m"
version = "0.1.0"
edition = "2024"

[dependencies]
taskette = { path = "../taskette" }
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"
critical-section = "1.2.0"
heapless = "0.9.1"
log = "0.4.28"